// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/vootoo/client/netty/protocol/solr.proto

package org.vootoo.client.netty.protocol;

public final class SolrProtocol {
  private SolrProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SolrRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rid = 1;
    /**
     * <code>required int64 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int64 rid = 1;</code>
     */
    long getRid();

    // optional string coreName = 2;
    /**
     * <code>optional string coreName = 2;</code>
     */
    boolean hasCoreName();
    /**
     * <code>optional string coreName = 2;</code>
     */
    java.lang.String getCoreName();
    /**
     * <code>optional string coreName = 2;</code>
     */
    com.google.protobuf.ByteString
        getCoreNameBytes();

    // required string path = 3;
    /**
     * <code>required string path = 3;</code>
     */
    boolean hasPath();
    /**
     * <code>required string path = 3;</code>
     */
    java.lang.String getPath();
    /**
     * <code>required string path = 3;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    // required bytes params = 4;
    /**
     * <code>required bytes params = 4;</code>
     */
    boolean hasParams();
    /**
     * <code>required bytes params = 4;</code>
     */
    com.google.protobuf.ByteString getParams();

    // repeated bytes streams = 5;
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getStreamsList();
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    int getStreamsCount();
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    com.google.protobuf.ByteString getStreams(int index);
  }
  /**
   * Protobuf type {@code org.vootoo.client.netty.protocol.SolrRequest}
   */
  public static final class SolrRequest extends
      com.google.protobuf.GeneratedMessage
      implements SolrRequestOrBuilder {
    // Use SolrRequest.newBuilder() to construct.
    private SolrRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SolrRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SolrRequest defaultInstance;
    public static SolrRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SolrRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SolrRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              coreName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              path_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              params_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                streams_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              streams_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          streams_ = java.util.Collections.unmodifiableList(streams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.class, org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SolrRequest> PARSER =
        new com.google.protobuf.AbstractParser<SolrRequest>() {
      public SolrRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SolrRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SolrRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    /**
     * <code>required int64 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rid = 1;</code>
     */
    public long getRid() {
      return rid_;
    }

    // optional string coreName = 2;
    public static final int CORENAME_FIELD_NUMBER = 2;
    private java.lang.Object coreName_;
    /**
     * <code>optional string coreName = 2;</code>
     */
    public boolean hasCoreName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string coreName = 2;</code>
     */
    public java.lang.String getCoreName() {
      java.lang.Object ref = coreName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          coreName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string coreName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCoreNameBytes() {
      java.lang.Object ref = coreName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coreName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string path = 3;
    public static final int PATH_FIELD_NUMBER = 3;
    private java.lang.Object path_;
    /**
     * <code>required string path = 3;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string path = 3;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes params = 4;
    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>required bytes params = 4;</code>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes params = 4;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    // repeated bytes streams = 5;
    public static final int STREAMS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> streams_;
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getStreamsList() {
      return streams_;
    }
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    public int getStreamsCount() {
      return streams_.size();
    }
    /**
     * <code>repeated bytes streams = 5;</code>
     */
    public com.google.protobuf.ByteString getStreams(int index) {
      return streams_.get(index);
    }

    private void initFields() {
      rid_ = 0L;
      coreName_ = "";
      path_ = "";
      params_ = com.google.protobuf.ByteString.EMPTY;
      streams_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCoreNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, params_);
      }
      for (int i = 0; i < streams_.size(); i++) {
        output.writeBytes(5, streams_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCoreNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, params_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < streams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(streams_.get(i));
        }
        size += dataSize;
        size += 1 * getStreamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.vootoo.client.netty.protocol.SolrRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.vootoo.client.netty.protocol.SolrProtocol.SolrRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.class, org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.Builder.class);
      }

      // Construct using org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        coreName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor;
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest getDefaultInstanceForType() {
        return org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.getDefaultInstance();
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest build() {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest buildPartial() {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest result = new org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coreName_ = coreName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.params_ = params_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          streams_ = java.util.Collections.unmodifiableList(streams_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.streams_ = streams_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest) {
          return mergeFrom((org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest other) {
        if (other == org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasCoreName()) {
          bitField0_ |= 0x00000002;
          coreName_ = other.coreName_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000004;
          path_ = other.path_;
          onChanged();
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        if (!other.streams_.isEmpty()) {
          if (streams_.isEmpty()) {
            streams_ = other.streams_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureStreamsIsMutable();
            streams_.addAll(other.streams_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        if (!hasPath()) {
          
          return false;
        }
        if (!hasParams()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.vootoo.client.netty.protocol.SolrProtocol.SolrRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rid = 1;
      private long rid_ ;
      /**
       * <code>required int64 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0L;
        onChanged();
        return this;
      }

      // optional string coreName = 2;
      private java.lang.Object coreName_ = "";
      /**
       * <code>optional string coreName = 2;</code>
       */
      public boolean hasCoreName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string coreName = 2;</code>
       */
      public java.lang.String getCoreName() {
        java.lang.Object ref = coreName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          coreName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string coreName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCoreNameBytes() {
        java.lang.Object ref = coreName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coreName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string coreName = 2;</code>
       */
      public Builder setCoreName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        coreName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string coreName = 2;</code>
       */
      public Builder clearCoreName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coreName_ = getDefaultInstance().getCoreName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string coreName = 2;</code>
       */
      public Builder setCoreNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        coreName_ = value;
        onChanged();
        return this;
      }

      // required string path = 3;
      private java.lang.Object path_ = "";
      /**
       * <code>required string path = 3;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string path = 3;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string path = 3;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 3;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 3;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }

      // required bytes params = 4;
      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes params = 4;</code>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes params = 4;</code>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>required bytes params = 4;</code>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes params = 4;</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      // repeated bytes streams = 5;
      private java.util.List<com.google.protobuf.ByteString> streams_ = java.util.Collections.emptyList();
      private void ensureStreamsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          streams_ = new java.util.ArrayList<com.google.protobuf.ByteString>(streams_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getStreamsList() {
        return java.util.Collections.unmodifiableList(streams_);
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public int getStreamsCount() {
        return streams_.size();
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public com.google.protobuf.ByteString getStreams(int index) {
        return streams_.get(index);
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public Builder setStreams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStreamsIsMutable();
        streams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public Builder addStreams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStreamsIsMutable();
        streams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public Builder addAllStreams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureStreamsIsMutable();
        super.addAll(values, streams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 5;</code>
       */
      public Builder clearStreams() {
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.vootoo.client.netty.protocol.SolrRequest)
    }

    static {
      defaultInstance = new SolrRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.vootoo.client.netty.protocol.SolrRequest)
  }

  public interface SolrResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rid = 1;
    /**
     * <code>required int64 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int64 rid = 1;</code>
     */
    long getRid();

    // optional int32 responseFormat = 2;
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     * 1=javabin, 2=json, 3=csv
     * 10=xml, 11=php, 12=phps
     * </pre>
     */
    boolean hasResponseFormat();
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     * 1=javabin, 2=json, 3=csv
     * 10=xml, 11=php, 12=phps
     * </pre>
     */
    int getResponseFormat();

    // optional bytes response = 3;
    /**
     * <code>optional bytes response = 3;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 3;</code>
     */
    com.google.protobuf.ByteString getResponse();

    // optional int32 errorCode = 4;
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    int getErrorCode();

    // optional string errorStr = 5;
    /**
     * <code>optional string errorStr = 5;</code>
     */
    boolean hasErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    java.lang.String getErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrorStrBytes();
  }
  /**
   * Protobuf type {@code org.vootoo.client.netty.protocol.SolrResponse}
   */
  public static final class SolrResponse extends
      com.google.protobuf.GeneratedMessage
      implements SolrResponseOrBuilder {
    // Use SolrResponse.newBuilder() to construct.
    private SolrResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SolrResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SolrResponse defaultInstance;
    public static SolrResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SolrResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SolrResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              responseFormat_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              response_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              errorCode_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              errorStr_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.class, org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SolrResponse> PARSER =
        new com.google.protobuf.AbstractParser<SolrResponse>() {
      public SolrResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SolrResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SolrResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    /**
     * <code>required int64 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rid = 1;</code>
     */
    public long getRid() {
      return rid_;
    }

    // optional int32 responseFormat = 2;
    public static final int RESPONSEFORMAT_FIELD_NUMBER = 2;
    private int responseFormat_;
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     * 1=javabin, 2=json, 3=csv
     * 10=xml, 11=php, 12=phps
     * </pre>
     */
    public boolean hasResponseFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     * 1=javabin, 2=json, 3=csv
     * 10=xml, 11=php, 12=phps
     * </pre>
     */
    public int getResponseFormat() {
      return responseFormat_;
    }

    // optional bytes response = 3;
    public static final int RESPONSE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 3;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes response = 3;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    // optional int32 errorCode = 4;
    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    // optional string errorStr = 5;
    public static final int ERRORSTR_FIELD_NUMBER = 5;
    private java.lang.Object errorStr_;
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public boolean hasErrorStr() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public java.lang.String getErrorStr() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrorStrBytes() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rid_ = 0L;
      responseFormat_ = 0;
      response_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = 0;
      errorStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, response_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, errorCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getErrorStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, response_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, errorCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getErrorStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.vootoo.client.netty.protocol.SolrResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.vootoo.client.netty.protocol.SolrProtocol.SolrResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.class, org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.Builder.class);
      }

      // Construct using org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFormat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        errorStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.vootoo.client.netty.protocol.SolrProtocol.internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor;
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse getDefaultInstanceForType() {
        return org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.getDefaultInstance();
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse build() {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse buildPartial() {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse result = new org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseFormat_ = responseFormat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorStr_ = errorStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse) {
          return mergeFrom((org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse other) {
        if (other == org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasResponseFormat()) {
          setResponseFormat(other.getResponseFormat());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorStr()) {
          bitField0_ |= 0x00000010;
          errorStr_ = other.errorStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.vootoo.client.netty.protocol.SolrProtocol.SolrResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rid = 1;
      private long rid_ ;
      /**
       * <code>required int64 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 responseFormat = 2;
      private int responseFormat_ ;
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       * 1=javabin, 2=json, 3=csv
       * 10=xml, 11=php, 12=phps
       * </pre>
       */
      public boolean hasResponseFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       * 1=javabin, 2=json, 3=csv
       * 10=xml, 11=php, 12=phps
       * </pre>
       */
      public int getResponseFormat() {
        return responseFormat_;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       * 1=javabin, 2=json, 3=csv
       * 10=xml, 11=php, 12=phps
       * </pre>
       */
      public Builder setResponseFormat(int value) {
        bitField0_ |= 0x00000002;
        responseFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       * 1=javabin, 2=json, 3=csv
       * 10=xml, 11=php, 12=phps
       * </pre>
       */
      public Builder clearResponseFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseFormat_ = 0;
        onChanged();
        return this;
      }

      // optional bytes response = 3;
      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 3;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000004);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      // optional int32 errorCode = 4;
      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000008;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      // optional string errorStr = 5;
      private java.lang.Object errorStr_ = "";
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public boolean hasErrorStr() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public java.lang.String getErrorStr() {
        java.lang.Object ref = errorStr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrorStrBytes() {
        java.lang.Object ref = errorStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder clearErrorStr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorStr_ = getDefaultInstance().getErrorStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorStr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.vootoo.client.netty.protocol.SolrResponse)
    }

    static {
      defaultInstance = new SolrResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.vootoo.client.netty.protocol.SolrResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_vootoo_client_netty_protocol_SolrRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_vootoo_client_netty_protocol_SolrResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+org/vootoo/client/netty/protocol/solr." +
      "proto\022 org.vootoo.client.netty.protocol\"" +
      "[\n\013SolrRequest\022\013\n\003rid\030\001 \002(\003\022\020\n\010coreName\030" +
      "\002 \001(\t\022\014\n\004path\030\003 \002(\t\022\016\n\006params\030\004 \002(\014\022\017\n\007s" +
      "treams\030\005 \003(\014\"j\n\014SolrResponse\022\013\n\003rid\030\001 \002(" +
      "\003\022\026\n\016responseFormat\030\002 \001(\005\022\020\n\010response\030\003 " +
      "\001(\014\022\021\n\terrorCode\030\004 \001(\005\022\020\n\010errorStr\030\005 \001(\t" +
      "B2\n org.vootoo.client.netty.protocolB\014So" +
      "lrProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_vootoo_client_netty_protocol_SolrRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_vootoo_client_netty_protocol_SolrRequest_descriptor,
              new java.lang.String[] { "Rid", "CoreName", "Path", "Params", "Streams", });
          internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_vootoo_client_netty_protocol_SolrResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_vootoo_client_netty_protocol_SolrResponse_descriptor,
              new java.lang.String[] { "Rid", "ResponseFormat", "Response", "ErrorCode", "ErrorStr", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
